//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDPersonas.svrPersona {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="svrPersona.IsvcPersona")]
    public interface IsvcPersona {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsvcPersona/Insertar", ReplyAction="http://tempuri.org/IsvcPersona/InsertarResponse")]
        void Insertar(CapaBO.PersonaBO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsvcPersona/Insertar", ReplyAction="http://tempuri.org/IsvcPersona/InsertarResponse")]
        System.Threading.Tasks.Task InsertarAsync(CapaBO.PersonaBO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsvcPersona/Actualizar", ReplyAction="http://tempuri.org/IsvcPersona/ActualizarResponse")]
        void Actualizar(CapaBO.PersonaBO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsvcPersona/Actualizar", ReplyAction="http://tempuri.org/IsvcPersona/ActualizarResponse")]
        System.Threading.Tasks.Task ActualizarAsync(CapaBO.PersonaBO pPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsvcPersona/Eliminar", ReplyAction="http://tempuri.org/IsvcPersona/EliminarResponse")]
        void Eliminar(int pIdPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsvcPersona/Eliminar", ReplyAction="http://tempuri.org/IsvcPersona/EliminarResponse")]
        System.Threading.Tasks.Task EliminarAsync(int pIdPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsvcPersona/Consultar", ReplyAction="http://tempuri.org/IsvcPersona/ConsultarResponse")]
        CapaBO.PersonaBO[] Consultar(System.Nullable<int> pIdPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsvcPersona/Consultar", ReplyAction="http://tempuri.org/IsvcPersona/ConsultarResponse")]
        System.Threading.Tasks.Task<CapaBO.PersonaBO[]> ConsultarAsync(System.Nullable<int> pIdPersona);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IsvcPersonaChannel : CRUDPersonas.svrPersona.IsvcPersona, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IsvcPersonaClient : System.ServiceModel.ClientBase<CRUDPersonas.svrPersona.IsvcPersona>, CRUDPersonas.svrPersona.IsvcPersona {
        
        public IsvcPersonaClient() {
        }
        
        public IsvcPersonaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IsvcPersonaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsvcPersonaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IsvcPersonaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Insertar(CapaBO.PersonaBO pPersona) {
            base.Channel.Insertar(pPersona);
        }
        
        public System.Threading.Tasks.Task InsertarAsync(CapaBO.PersonaBO pPersona) {
            return base.Channel.InsertarAsync(pPersona);
        }
        
        public void Actualizar(CapaBO.PersonaBO pPersona) {
            base.Channel.Actualizar(pPersona);
        }
        
        public System.Threading.Tasks.Task ActualizarAsync(CapaBO.PersonaBO pPersona) {
            return base.Channel.ActualizarAsync(pPersona);
        }
        
        public void Eliminar(int pIdPersona) {
            base.Channel.Eliminar(pIdPersona);
        }
        
        public System.Threading.Tasks.Task EliminarAsync(int pIdPersona) {
            return base.Channel.EliminarAsync(pIdPersona);
        }
        
        public CapaBO.PersonaBO[] Consultar(System.Nullable<int> pIdPersona) {
            return base.Channel.Consultar(pIdPersona);
        }
        
        public System.Threading.Tasks.Task<CapaBO.PersonaBO[]> ConsultarAsync(System.Nullable<int> pIdPersona) {
            return base.Channel.ConsultarAsync(pIdPersona);
        }
    }
}
